
const serviceGroups = [
  {
    id: "1",
    name: "ትምህርት ክፍል",
    description:
      "Handles spiritual teaching, bible studies and education programs.",
    admin_name: "Teacher Leader",
    members: 45,
    active: 30,
    leaders: 5,
    subgroups: [
      { title: "Bible Study", desc: "Weekly bible study sessions." },
      { title: "Youth Teaching", desc: "Teaching youth spiritual topics." },
    ],
  },
  {
    id: "2",
    name: "አባላት እና እንክብካቤ ክፍል",
    description:
      "Responsible for caring for members and welcoming new believers.",
    admin_name: "Care Leader",
    members: 30,
    active: 20,
    leaders: 4,
    subgroups: [
      { title: "Home Visits", desc: "Visiting members and supporting them." },
    ],
  },
  {
    id: "3",
    name: "ልማት ክፍል",
    description: "Handles church development projects and infrastructure.",
    admin_name: "Development Leader",
    members: 25,
    active: 15,
    leaders: 3,
    subgroups: [
      { title: "Building Team", desc: "Church building improvements." },
    ],
  },
  {
    id: "4",
    name: "መዝሙር ክፍል",
    description: "Choir and worship ministry.",
    admin_name: "Choir Leader",
    members: 60,
    active: 40,
    leaders: 6,
    subgroups: [{ title: "Main Choir", desc: "Sunday worship choir." }],
  },
  {
    id: "5",
    name: "ሙያ እና ተራድኦ",
    description: "Professional support and volunteering activities.",
    admin_name: "Volunteer Leader",
    members: 20,
    active: 12,
    leaders: 2,
    subgroups: [{ title: "Volunteer Team", desc: "Helping church events." }],
  },
  {
    id: "6",
    name: "ቁዋንቁዋና ልዩ ልዩ ክፍል",
    description: "Handles language and translation services.",
    admin_name: "Language Leader",
    members: 15,
    active: 10,
    leaders: 2,
    subgroups: [{ title: "Translation", desc: "Translating sermons." }],
  },
  {
    id: "7",
    name: "ሂሳብ ክፍል",
    description: "Finance and accounting department.",
    admin_name: "Finance Leader",
    members: 12,
    active: 8,
    leaders: 2,
    subgroups: [{ title: "Budget Team", desc: "Managing church finances." }],
  },
  {
    id: "8",
    name: "ኦዲት ክፍል",
    description: "Audit and transparency management.",
    admin_name: "Audit Leader",
    members: 10,
    active: 6,
    leaders: 2,
    subgroups: [{ title: "Review Team", desc: "Reviewing financial records." }],
  },
  {
    id: "9",
    name: "ባች እና መርሃግብር",
    description: "Program planning and scheduling.",
    admin_name: "Program Leader",
    members: 18,
    active: 12,
    leaders: 3,
    subgroups: [
      { title: "Planning Team", desc: "Organizing church programs." },
    ],
  },
  {
    id: "10",
    name: "መረጃ እና ክትትል ክፍል",
    description: "Information management and follow-up.",
    admin_name: "Information Leader",
    members: 22,
    active: 14,
    leaders: 3,
    subgroups: [{ title: "Data Team", desc: "Managing church records." }],
  },
];

