# Generated by Django 5.1 on 2026-03-04 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_service_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgeglotSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'First Choice'), (2, 'Second Choice'), (3, 'Third Choice')])),
                ('skills', models.TextField(blank=True, help_text='Relevant talents/skills', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for selection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_selections', to=settings.AUTH_USER_MODEL)),
                ('service_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='service.servicegroup')),
            ],
            options={
                'ordering': ['student', 'priority'],
                'unique_together': {('student', 'priority'), ('student', 'service_group')},
            },
        ),
    ]
