# Generated by Django 5.1 on 2026-03-04 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selection_open', models.BooleanField(default=False, help_text='Open service group selection for students')),
            ],
            options={
                'verbose_name_plural': 'Service Configuration',
            },
        ),
        migrations.CreateModel(
            name='ServiceGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('LEADER', 'Leader'), ('COORDINATOR', 'Coordinator')], default='MEMBER', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROBATION', 'Probation'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('service_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='service.servicegroup')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=20)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='service.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event__start_date', 'student'],
                'unique_together': {('event', 'student')},
            },
        ),
    ]
