# Generated by Django 5.1 on 2026-03-04 03:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('baptismal_name', models.CharField(blank=True, help_text='ክርስትና ስም', max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('batch_year', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=50, null=True)),
                ('personal_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('home_address', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_church', models.CharField(blank=True, max_length=150, null=True)),
                ('activity_serving', models.CharField(blank=True, help_text='Current church role', max_length=150, null=True)),
                ('dorm_block', models.PositiveIntegerField(blank=True, help_text='Block Number', null=True)),
                ('dorm_room', models.PositiveIntegerField(blank=True, help_text='Room Number', null=True)),
                ('confession_father', models.CharField(blank=True, help_text='የንስሐ አባት ስም', max_length=100, null=True)),
                ('status', models.CharField(choices=[('IN_CAMPUS', 'In Campus'), ('GRADUATED', 'Graduated')], default='IN_CAMPUS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
