# Generated by Django 5.1 on 2026-03-04 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='baptismal_name',
        ),
    ]
