# Generated by Django 5.1 on 2026-03-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Student', 'Student'), ('FamilyAdmin', 'Family Admin'), ('ServiceAdmin', 'Service Admin'), ('SuperAdmin', 'Super Admin')], max_length=50, unique=True),
        ),
    ]
