# Generated by Django 5.1 on 2026-03-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionanswer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Moderation flag'),
        ),
    ]
